#81 Verified member. Refactoring
pivorakmeetup/pivorak-web-app pull request #113
Opened 2016-12-29 18:20 UTC by sveredyuk

Fixed #81

@denysmedynskyi a little bit refactored your code. Tried to prettify admin area

2016-12-29 20:18 UTC, denysmedynskyi commented on app/views/admin/visit_requests/index.slim
> +            - if visit_request.canceled?
visit request had 3 statuses, so I suggest to use if statements

2016-12-29 20:19 UTC, denys-medynskyi requested changes

2016-12-29 20:19 UTC, denysmedynskyi commented on app/views/admin/visit_requests/index.slim
> +              = admin_approve_visit_request_link(event, visit_request)
what if visit request status is `pending` ?

2016-12-30 05:23 UTC, sveredyuk commented on app/views/admin/visit_requests/index.slim
> +              = admin_approve_visit_request_link(event, visit_request)
Ofc, if canceled -> approve, if pending or approved -> cancel. Everything fine.

2016-12-30 12:13 UTC, denys-medynskyi approved these changes

2016-12-30 20:02 UTC, merged