#69 add default hours for event
pivorakmeetup/pivorak-web-app pull request #149
Opened 2017-01-24 09:58 UTC by oookli

2017-01-24 10:00 UTC, sveredyuk commented on app/controllers/admin/events_controller.rb
> +        started_at: date_with_specified_hour(Event::DEFAULT_STARTED_AT_HOURS),
this looks like business logic in controller. Bad.
Try extract this logic to service like `@event = Event::New.call` and let service to rule logic

2017-01-24 10:09 UTC, oookli commented on app/controllers/admin/events_controller.rb
> +        started_at: date_with_specified_hour(Event::DEFAULT_STARTED_AT_HOURS),
ok, thanks, I'll fix it

2017-01-24 15:17 UTC, oookli commented on app/controllers/admin/events_controller.rb
> +        started_at: date_with_specified_hour(Event::DEFAULT_STARTED_AT_HOURS),
@sveredyuk I've updated it, please check if everything is ok

2017-01-24 16:14 UTC, kushniryb commented on app/services/event/new.rb
> +      DateTime.now.change({hour: hour, min: 0, sec: 0})
1. There's no need to use `{}` here
2. Check the method [source](http://apidock.com/rails/DateTime/change) - you can just write `DateTime.now.change(hour: 0)`, minutes and seconds will be 0 by default

2017-01-24 16:17 UTC, kushniryb commented on app/services/event/new.rb
> +
Remove space here

2017-01-24 16:20 UTC, kushniryb commented on app/services/event/new.rb
> +
There's no need for an empty line here

2017-01-24 16:23 UTC, kushniryb commented on app/services/event/new.rb
> +      DateTime.now.change({hour: hour, min: 0, sec: 0})
Also, use `Time.zone.now`. Article for [reference](http://danilenko.org/2012/7/6/rails_timezones/)

2017-01-24 16:26 UTC, kushniryb commented on app/services/event/new.rb
> +end
Also, I'm not sure it's worth creating a separate class which just sets 2 attributes, maybe an `after_initialize`hook would be better? What do you think @sveredyuk @denysmedynskyi

2017-01-24 16:27 UTC, kushniryb requested changes
Please, fix a few issues described above

2017-01-24 16:40 UTC, oookli commented on app/services/event/new.rb
> +
okok

2017-01-24 16:41 UTC, oookli commented on app/services/event/new.rb
> +      DateTime.now.change({hour: hour, min: 0, sec: 0})
thanks @kushniryb , I'll fix this issues

2017-01-24 16:46 UTC, oookli commented on app/services/event/new.rb
> +end
@kushniryb but `after_initialize` not very transparently, I think

2017-01-24 17:59 UTC, denysmedynskyi commented on app/services/event/new.rb
> +end
Callbacks are not good for health. I prefer not to use `after_initialize`

2017-01-24 19:33 UTC, sveredyuk commented on app/services/event/new.rb
> +  class New
inherit form ApplicationService

2017-01-24 19:33 UTC, sveredyuk commented on app/services/event/new.rb
> +      new.call
ApplicationService class inheritance goves you this factory method for free

2017-01-24 19:33 UTC, sveredyuk commented on app/services/event/new.rb
> +end
agree with @denysmedynskyi callbacks are evil. Clear invocation are better than magical `after_some_wtf_when_where_why_shit`

2017-01-24 22:11 UTC, kushniryb commented on app/services/event/new.rb
> +end
Yeah, callbacks are evil, I agree, but creating this kind of an object to populate 2 fields seems like an overkill to me. Also, why not Form Object here?

2017-01-24 22:14 UTC, sveredyuk commented on app/services/event/new.rb
> +end
@kushniryb FormObject will rule this in version when we rewrite all this to Trailblazer and than cut to engines )

2017-01-30 13:08 UTC, oookli commented
I have updated this branch already, thanks for responses

2017-01-30 13:10 UTC, sveredyuk approved these changes
Resolve conflicts
Improve test cove up to 100%

2017-01-30 13:25 UTC, oookli commented
![image](https://cloud.githubusercontent.com/assets/1590773/22424643/131ee032-e700-11e6-8925-3a48c5fcf2aa.png)
@sveredyuk we updated this values, we should use some datetimepicker in future?

2017-01-30 13:33 UTC, sveredyuk commented
@oookli Ofc #158

2017-01-30 13:53 UTC, oookli commented
@sveredyuk Could I take that?

2017-01-31 07:32 UTC, kushniryb approved these changes

2017-01-31 07:39 UTC, sveredyuk commented
@oookli does it ready for merge ?

2017-01-31 07:42 UTC, oookli commented
@sveredyuk yes, I think

2017-01-31 07:57 UTC, sveredyuk commented
@oookli merge

2017-01-31 07:58 UTC, oookli commented
@sveredyuk thanks

2017-01-31 09:30 UTC, merged