#89 Donation page
pivorakmeetup/pivorak-web-app pull request #157
Opened 2017-01-28 15:11 UTC by sveredyuk

Fixed #89 

@kushniryb Sorry, bro. For 1.0 version was decided skip goals, as they requires unique page design per goal. So i just commented a lot of your code. But used payment process for simple donation process. In next version we'll able to unblock goals for main app

2017-01-29 07:47 UTC, denysmedynskyi commented on app/controllers/donates_controller.rb
> +class DonatesController < ApplicationController
I suggest to use `DonationsController` as name, because our domain model is `Donation`

2017-01-29 07:48 UTC, denysmedynskyi commented on app/controllers/donates_controller.rb
> +    result = Goal::Donations::Create.call(donation_params)
Regarding `Donations` - I thought we had a deal, that we use only singular form. Am I right ?

2017-01-29 07:49 UTC, denysmedynskyi commented on app/helpers/navigation_helper.rb
> +    link_to t('donations.donate'), donate_path
and here I see `donate_path`. It would more consistent if you used `donations_path`

2017-01-29 07:49 UTC, denysmedynskyi commented on config/routes.rb
> +  resource :donate, only: %i[show create]
and donations resource

2017-01-29 07:50 UTC, denys-medynskyi requested changes
cool, but I have suggestions about inconsistency - `donate` vs `donation`

2017-02-05 17:57 UTC, kushniryb commented
@sveredyuk shit happens :smiling_imp:

2017-02-05 17:58 UTC, kushniryb approved these changes
Regarding the code - everything looks good
Regarding the naming - we should use `Donation` as @denysmedynskyi already mentioned

2017-02-09 12:09 UTC, sveredyuk commented
@denysmedynskyi Donate -> Donation. Done.

2017-02-09 13:58 UTC, merged