Filter admin members
pivorakmeetup/pivorak-web-app pull request #311
Opened 2017-04-10 13:21 UTC by denysmedynskyi

2017-04-10 13:31 UTC, floor114 approved these changes

2017-04-10 16:55 UTC, sveredyuk approved these changes

2017-04-10 20:37 UTC, kushniryb commented on app/views/admin/members/index.slim
> +        = f.input attribute, as: :boolean
Add `unchecked_value: false` here so that disabled check-boxes aren't submitted

2017-04-10 20:37 UTC, kushniryb commented on app/finders/user/filtered.rb
> +        .keep_if { |_, value| parse_boolean(value) }
No need for this line, take a look at my comment below

2017-04-10 20:39 UTC, kushniryb commented on app/finders/user/filtered.rb
> +      ActiveRecord::Type::Boolean.new.deserialize(value)
No need for this method as well, you can check for the presence of the key instead

2017-04-10 20:47 UTC, kushniryb commented on spec/features/admin/members/list_spec.rb
> +      let!(:non_speaker) {create(:user)}
can we get some spaces here and above? :)

2017-04-10 20:49 UTC, kushniryb requested changes
Please, add `unchecked_value: false` to the simple_form input options, it'll greatly reduce the amount of code required

2017-04-11 06:21 UTC, denysmedynskyi commented on spec/features/admin/members/list_spec.rb
> +      let!(:non_speaker) {create(:user)}
do you mean only `let!(:non_speaker)` or each `setup` / `spec` block ?

2017-04-11 07:45 UTC, kushniryb commented on spec/features/admin/members/list_spec.rb
> +      let!(:non_speaker) {create(:user)}
Yes, only `let!` so that there's space between curly brace and `create`

2017-04-11 07:45 UTC, kushniryb approved these changes
Looks good :+1:

2017-04-11 07:47 UTC, sveredyuk commented on spec/features/admin/members/list_spec.rb
> +      let!(:non_speaker) {create(:user)}
I call this. fengshui style (c)
```ruby
let!(:non_speaker) { create :user }
```

2017-04-11 07:49 UTC, sveredyuk commented
@denysmedynskyi merge. We need deploy new version.

2017-04-15 06:15 UTC, denysmedynskyi commented on spec/features/admin/members/list_spec.rb
> +      let!(:non_speaker) {create(:user)}
I will add rubocop rule to prevent such things

2017-04-15 06:25 UTC, merged