Add search to the index talks page
pivorakmeetup/pivorak-web-app pull request #456
Opened 2017-07-18 05:51 UTC by Sayok

Resolves [github issue](https://github.com/pivorakmeetup/pivorak-web-app/issues/x)

### Description

there is no search bar on the pivorak.com/talks page, it should be added to have navigation through talks faster.

Describe the changes and motivations for the pull request, unless obvious from the title.

a search bar has been added to the pivorak.com/talks page, test steps and changes are described below.

### How to test instructions

1. go to /talks page
2. verify that search bar shown up on the page (see attachments)
3. put some title of the talks and press search button
4. talks with appropriated title or description should be shown up on the page.

### Pre-merge checklist
 
- [ improvement] The PR relates to a single subject with a clear title and description
- [ +] Verify that feature branch is up-to-date with `development` (if not - rebase it). 

### Screenshots

| Before                                      | After                                       |
| ------------------------------------------- | ------------------------------------------- |
| 
![before_talks](https://user-images.githubusercontent.com/10061671/28302479-393e4fc6-6b96-11e7-9d05-71472acf099a.png)
 | 
![after_search](https://user-images.githubusercontent.com/10061671/28302485-4098d7aa-6b96-11e7-96a7-e656707f195b.png)
 |

2017-07-18 05:55 UTC, sveredyuk commented on spec/features/talks/search_spec.rb
> +  let!(:talk_1) { create :talk, title: 'Talk 1', description: "infrastructure", event: event }
`let!(:talk_1) { create :talk, title: title_of_talk_1', description: "infrastructure", event: event }`
and cetera

2017-07-18 10:18 UTC, denys-medynskyi requested changes
Good from the code perspective.
However, you forgot to add text when no results are present. Please add feature spec for this.
How to reproduce:
Visit - http://localhost:3000/talks?utf8=%E2%9C%93&query=asdada
Check this screenshot : https://cl.ly/3t42051N2r0a

2017-07-18 13:02 UTC, Sayok commented
{quote } @denysmedynskyi However, you forgot to add text when no results are present. Please add feature spec for this. {quote}

will fix it soon.

2017-07-26 10:01 UTC, denys-medynskyi approved these changes
Nice! Thank you.

2017-07-26 10:02 UTC, denysmedynskyi commented
I am going to merge it after CI is green

2017-07-27 02:40 UTC, merged