#204 Improve user profile
pivorakmeetup/pivorak-web-app pull request #477
Opened 2017-07-21 10:40 UTC by Sontsevolosa

Resolves [github issue](https://github.com/pivorakmeetup/pivorak-web-app/issues/204)

### Description

- Add count of sign in to the user profile
- Add 'pk-container' class to the user profile page
- Add localization for text
- Add styles from form for user sign in
- Add test for check if page have 'Count of sign in' text

### How to test instructions

rspec spec/features/profile

### Pre-merge checklist
 
- [ ] The PR relates to a single subject with a clear title and description
- [ ] Verify that feature branch is up-to-date with `development` (if not - rebase it). 

### Screenshots

![profile_before](https://user-images.githubusercontent.com/15029139/28460164-7d1f3c3e-6e19-11e7-9563-e896863c1da6.png)
![profile_after](https://user-images.githubusercontent.com/15029139/28460180-9225c2ec-6e19-11e7-8a6d-b1322cec2617.png)
![edit_before](https://user-images.githubusercontent.com/15029139/28460205-b3cd5b3a-6e19-11e7-8f7b-b76064079599.png)
![edit_after](https://user-images.githubusercontent.com/15029139/28460218-c65b3f9c-6e19-11e7-8b7e-a1083e781ec9.png)

2017-07-24 10:35 UTC, denysmedynskyi commented on app/views/members/_profile.slim
> +  = current_user.sign_in_count
Do we really need this sign in counter?

2017-07-24 10:36 UTC, denys-medynskyi requested changes
Everything looks good!
However, I have 3 questions/suggesstions:
- [ ] Do we need sign in counter?
- [ ] How can I access this page via link?
- [ ] Please, rebase your branch on master to make CI pass.

2017-07-26 08:29 UTC, Sontsevolosa commented
@denysmedynskyi please, review my changes)

2017-07-26 10:06 UTC, denys-medynskyi requested changes
Can you add the same color background as [here](https://pivorak.com/users/sign_in)  and put fields on the center of the screen?
By the way, you can argue with me if you disagree.

2017-07-26 14:12 UTC, Sontsevolosa commented
@denysmedynskyi please, review my code)

2017-07-27 02:40 UTC, denysmedynskyi commented on .travis.yml
> -language:
Just rebase this branch on development, so you will not need to add this manually.

2017-07-27 18:39 UTC, Sontsevolosa commented
@denysmedynskyi please, review my code

2017-07-28 06:12 UTC, denysmedynskyi commented on app/views/profile/edit.slim
> +    /<div style="
Remove commented code

2017-07-28 06:13 UTC, denys-medynskyi requested changes
After update profile notification message is wrong.
Can you fix it?
After update I see this - https://cl.ly/3y2V1L2W0J3g.
I think it just needs some string in en.yml file

2017-07-28 06:15 UTC, denysmedynskyi commented
Another thing - pivorak logo is missing on edit profile form - https://cl.ly/1k0422412z1u

2017-07-28 06:16 UTC, denysmedynskyi commented
This page looks ugly - https://cl.ly/0L2V2w1M3z0Z, so make `profile` link lead to `/profile/edit` or improve profile page

2017-07-28 07:45 UTC, sveredyuk commented
@denysmedynskyi Please..... man..... bro..... please.... review!

2017-07-28 11:55 UTC, Sontsevolosa commented
@denysmedynskyi please, review changes)

2017-07-29 11:40 UTC, denysmedynskyi commented
@sveredyuk are you asking me to review other PRs?

2017-07-29 12:38 UTC, denys-medynskyi approved these changes

2017-07-29 12:38 UTC, merged