#460 group visit requests
pivorakmeetup/pivorak-web-app pull request #480
Opened 2017-07-23 08:45 UTC by avozniak

Resolves [github issue #460 ](https://github.com/pivorakmeetup/pivorak-web-app/issues/460)

### Description

For better control of visit requests general list was separated to main list and waiting list

### How to test instructions
Go to visit requests page of any event
You shoud see two columns: main list and waiting list

### Pre-merge checklist
 
- [x] The PR relates to a single subject with a clear title and description
- [x] Verify that feature branch is up-to-date with `development` (if not - rebase it). 

### Screenshots

| Before                                      | After                                       |
| ------------------------------------------- | ------------------------------------------- |
| ![](http://pix.toile-libre.org/upload/original/1500799125.png) | ![](http://pix.toile-libre.org/upload/original/1500799197.png) |
| ![](http://pix.toile-libre.org/upload/original/1500799282.png) | ![](http://pix.toile-libre.org/upload/original/1500799331.png) |
| ![](http://pix.toile-libre.org/upload/original/1500799415.png) | ![](http://pix.toile-libre.org/upload/original/1500799477.png) |

2017-07-23 09:22 UTC, denysmedynskyi commented on app/views/admin/visit_requests/_main_list.slim
> +      th = 'Verified?'
Use `t('members.verified')`

2017-07-23 09:24 UTC, denysmedynskyi commented on app/views/admin/visit_requests/_waiting_list.slim
> +            Waiiting list
1. Typo
2. This text should be in .yml
3. use t('visit_requests.waiting_list')
4. Change  visit_requests.waiting_list' in `en.yml` to `Waiting list`

2017-07-23 09:27 UTC, denys-medynskyi requested changes
Fix locales & I will post one more bug as a separate comment

2017-07-23 09:28 UTC, denysmedynskyi commented
Waiting list partial does not have column headers, so ui looks ugly
https://cl.ly/0B3B132X0g2I

2018-06-20 12:19 UTC, sveredyuk commented
This page already changed a lot. That was a good practice but we cannot merge this anymore :(

2018-06-20 12:19 UTC, closed without merging