#303 Ddd donations list to the admin panel
pivorakmeetup/pivorak-web-app pull request #491
Opened 2017-07-26 16:15 UTC by Sontsevolosa

Resolves [github issue](https://github.com/pivorakmeetup/pivorak-web-app/issues/303)

### Description

- Add route for donations list to the routes.rb file
- Add link to donations list to the navigation helper
- Add link to donations list to the footer of admin panel
- Create Donations controller in the Admin scope
- Get list of all donations in 'donations' helper method in the Admin/Donations controller
- Add table with all donations to the view for 'index' action
- Add localization of 'Donator' word to the en.yml file
- Add pagination for donations
- Add breadcrumbs to the view for 'index' action
- Add test for checking list of donations on the page

### How to test instructions

rspec/spec/features/admin/donations

2017-07-26 16:16 UTC, Sontsevolosa commented
@denysmedynskyi please, review my PR 🙂

2017-07-27 02:51 UTC, denysmedynskyi commented on app/views/admin/donations/index.slim
> +        - if donation.user
You can do `user&.full_name || '-'` instead of `if`

2017-07-27 02:56 UTC, denysmedynskyi commented on app/views/admin/donations/index.slim
> +        td.center.aligned = donation.created_at.strftime("%d/%m/%Y")
Extract `%x%x%x` to en.yml. Check this [article](http://www.stackednotion.com/blog/2015/01/03/formatting-dates-and-times-in-rails-with-i18n-localize/)

2017-07-27 02:59 UTC, denys-medynskyi requested changes
Good job!
However, I have a few suggestions. In the code and one more in UI - https://cl.ly/2Y0l223L1N0P - to add `total` on the top of the page

2017-07-27 20:03 UTC, Sontsevolosa commented
@denysmedynskyi please, review my changes)

2017-07-28 06:10 UTC, denys-medynskyi approved these changes
Everything is great!
However, there is a thing about the PR description: how to test means - how to MANUALLY test your PR.

2017-07-28 06:17 UTC, merged