#506: Student can be graduated
pivorakmeetup/pivorak-web-app pull request #510
Opened 2017-07-28 13:28 UTC by NadiaGubernator

Resolves #506 
![screenshot from 2017-07-28 16-22-28](https://user-images.githubusercontent.com/28292743/28719225-cec964f4-73b1-11e7-9b1e-c69218197fff.png)

2017-07-28 13:32 UTC, sveredyuk commented on components/courses/app/helpers/admin/courses/season_helper.rb
> +        season.passed? && season.students.where(status: :attending).any?
to policy

2017-07-28 13:32 UTC, sveredyuk commented on components/courses/app/controllers/admin/courses/graduates_controller.rb
> +        current_season.students.where(status: :attending).update_all(status: :graduated)
to service

2017-07-29 12:05 UTC, denysmedynskyi commented on components/courses/app/policies/courses/season/graduate_students_policy.rb
> +        season.students.where(status: :attending).any?
`where(status: :attending)` is appearing in 2 places. You can use scope instead.

2017-07-29 12:07 UTC, denysmedynskyi commented on components/courses/spec/policies/courses/graduate/graduate_students_policy_spec.rb
> +  let (:season)  { create(:season, title: 'Test Season', status: :passed) }
1. You can use `described_class` which is equal to `Courses::Season::GraduateStudentsPolicy`
2. You can use [subject](https://relishapp.com/rspec/rspec-core/v/3-6/docs/subject/explicit-subject) like this:
`subject(:policy) {described_class.new(season)}`

2017-07-29 12:08 UTC, denys-medynskyi requested changes
Refactor a few things and everything will be good

2017-07-29 12:38 UTC, NadiaGubernator commented on components/courses/spec/policies/courses/graduate/graduate_students_policy_spec.rb
> +  let (:season)  { create(:season, title: 'Test Season', status: :passed) }
Neat!

2017-07-30 06:33 UTC, sveredyuk commented
@NadiaGubernator Looks like you rebased this branch with troubles :(

2017-07-31 04:47 UTC, NadiaGubernator commented
That's not it, pulling the branch from git resulted in conflicts and merge.

2017-07-31 05:35 UTC, NadiaGubernator commented
I've resolved that trouble, so no more sad smileys, please.

2017-07-31 06:05 UTC, sveredyuk commented
@NadiaGubernator conflicts

2017-07-31 06:16 UTC, NadiaGubernator commented
@sveredyuk done

2017-07-31 06:23 UTC, sveredyuk commented on components/courses/app/models/courses/student.rb
> +    scope     :attending, -> { where(status: :attending) }
remove -> http://api.rubyonrails.org/classes/ActiveRecord/Enum.html

2017-07-31 06:23 UTC, sveredyuk commented on components/courses/app/helpers/admin/courses/season_helper.rb
> +        ::Courses::Season::GraduateStudentsPolicy.new(season)
no policy in view helpers. move at least in controller

2017-07-31 06:23 UTC, sveredyuk commented on components/courses/app/views/admin/courses/seasons/show.slim
> +    = graduate_students_link(season) if graduate_policy(season).allowed?
enter before

2017-07-31 06:23 UTC, sveredyuk commented on components/courses/spec/features/admin/seasons/show_spec.rb
> +    let!(:student_a) { create(:student, status: :attending, season: season) }
avoid a/b when you could use attending_student or dropped_student

2017-07-31 06:23 UTC, sveredyuk commented on components/courses/spec/policies/courses/graduate/graduate_students_policy_spec.rb
> +  let!(:student)   { create(:student, season: season, status: :attending) }
let!(:student) too much space { ...

2017-07-31 06:37 UTC, NadiaGubernator commented on components/courses/app/models/courses/student.rb
> +    scope     :attending, -> { where(status: :attending) }
Are you sure it'll work like this?

2017-07-31 06:39 UTC, sveredyuk commented on components/courses/app/models/courses/student.rb
> +    scope     :attending, -> { where(status: :attending) }
I am sure that `ActiveRecord::Enumerator` creates scopes for you for free and you shouldn't duplicate it

2017-07-31 06:47 UTC, NadiaGubernator commented on components/courses/app/models/courses/student.rb
> +    scope     :attending, -> { where(status: :attending) }
I misinterpreted your comment then. Thanks for the explanation

2017-07-31 06:56 UTC, NadiaGubernator commented on components/courses/spec/policies/courses/graduate/graduate_students_policy_spec.rb
> +  let!(:student)   { create(:student, season: season, status: :attending) }
It is aligned with subject(:policy) { ...

2017-07-31 07:05 UTC, NadiaGubernator commented
@sveredyuk review pls :D

2017-07-31 07:09 UTC, sveredyuk approved these changes

2017-07-31 07:09 UTC, sveredyuk commented on components/courses/app/controllers/admin/courses/seasons_controller.rb
> +        ::Courses::Season::GraduateStudentsPolicy.new(season)
||=

2017-07-31 07:09 UTC, merged