Currency handling while donating.
pivorakmeetup/pivorak-web-app pull request #550
Opened 2018-01-31 15:52 UTC by ostaptan

Resolves [github issue](https://github.com/pivorakmeetup/pivorak-web-app/issues/498)

### Description

Gets currency from liqpay merchant and stores it in Donations table. (Added currency column for admin panel)

### How to test instructions
 
Run `rspec spec/services/liqpay/charge/handler_spec.rb`

### Pre-merge checklist
 
- [ ] The PR relates to a single subject with a clear title and description
- [ ] Verify that feature branch is up-to-date with `development` (if not - rebase it). 

### Screenshots

| Before                                      | After                                       |
| ------------------------------------------- | ------------------------------------------- |
| Insert screenshots and/or screen recordings | Insert screenshots and/or screen recordings |

2018-01-31 15:58 UTC, ostaptan commented
This needs more testing I guess. But it is not so obvious to find test suits. Needs more investigation of liqpay merchant.

2018-01-31 16:54 UTC, sveredyuk submitted a review, later dismissed
Well done

2018-02-05 11:50 UTC, kushniryb requested changes
A few small changes would be appreciated 🐧

2018-02-05 11:50 UTC, kushniryb commented on app/services/donation/create.rb
> +        amount:  data['amount'],
Table alignment would look good here.

2018-02-05 11:50 UTC, kushniryb commented on spec/factories/liqpay_factory.rb
> +    # currency   Faker::Currency.code why isnt this working?
Let's remove commented code.

2018-02-05 11:50 UTC, kushniryb commented on spec/services/liqpay/charge/handler_spec.rb
> +      let(:currency) { (build :liqpay_valid_response_data)[:currency] }
`build(:liqpay_valid_response_data)[:currency]` ?
Formatting looks weird.

2018-02-05 13:38 UTC, ostaptan commented on app/services/donation/create.rb
> +        amount:  data['amount'],
done

2018-02-12 10:18 UTC, kushniryb submitted a review, later dismissed
🐧

2018-02-12 10:44 UTC, sveredyuk approved these changes

2018-04-30 12:48 UTC, sveredyuk submitted a review, later dismissed

2018-12-29 12:32 UTC, denysmedynskyi commented
Liqpay is removed by wayforpay payments :(

2018-12-29 12:32 UTC, closed without merging