#37 Event visit request
pivorakmeetup/pivorak-web-app pull request #66
Opened 2016-12-19 06:16 UTC by denysmedynskyi

2016-12-20 06:53 UTC, sveredyuk requested changes
@denysmedynskyi Please, pay attention to all my comments

2016-12-20 06:53 UTC, sveredyuk commented on app/controllers/admin/visit_request/cancel_controller.rb
> +        @event ||= Event.friendly.find(params[:event_id])
DRY!
1. Create BaseController in VisitRequest module
2. extract this method
3. inherit controller from base

2016-12-20 06:53 UTC, sveredyuk commented on app/models/visit_request.rb
> +  PENDING = 'pending'
```ruby
enum status: %i[PENDING APPROVED CANCELED]
```

But keep symbols in constants

http://edgeapi.rubyonrails.org/classes/ActiveRecord/Enum.html

2016-12-20 06:53 UTC, sveredyuk commented on app/services/visit_request/finder/attendee.rb
> +        new(*args).call
you don't need this method

2016-12-20 06:53 UTC, sveredyuk commented on app/views/admin/events/index.slim
> +        td = link_to t('visit_requests.plural'), admin_event_visit_requests_path(event)
to `admin/events_helper.rb`

2016-12-20 06:53 UTC, sveredyuk commented on config/routes.rb
> +      patch :cancel, controller: 'visit_request/cancel', action: :update
Shorter version:
`patch :cancel, to: 'visit_request/cancel#update'`

2016-12-20 06:53 UTC, sveredyuk commented on config/routes.rb
> +          patch :cancel, controller: 'visit_request/cancel', action: :update
patch :approve, to: 'visit_request/approve#update'
patch :cancel, to: 'visit_request/cancel#update'

2016-12-20 06:53 UTC, sveredyuk commented on config/locales/en.yml
> +    create: 'Attend'
remove dup please

2016-12-20 06:53 UTC, sveredyuk commented on spec/features/visit_requests/create_spec.rb
> +
Why you always add this empty space before `end` ?
I think it's unnecessary

2016-12-20 06:53 UTC, sveredyuk commented on app/views/admin/visit_request/visit_requests/index.slim
> +        th = visit_request.user.full_name
this also must be a link to member profile with target: _blank

2016-12-20 06:53 UTC, sveredyuk commented on app/views/admin/visit_request/visit_requests/index.slim
> +        th = link_to t('visit_requests.cancel'), admin_event_visit_request_cancel_path(event, visit_request), method: :patch
Please, extract all link_to to admin/events_helper and keep template skinny

2016-12-20 06:53 UTC, sveredyuk commented on app/views/events/show.slim
> +- if visit_request
same... all to helpers

2016-12-20 08:50 UTC, sveredyuk commented
@denysmedynskyi rebase with development branch, new SimpleCov config may help

2016-12-25 08:23 UTC, denysmedynskyi commented
@sveredyuk please review again

2016-12-25 08:36 UTC, denysmedynskyi commented on app/views/events/show.slim
> +- if visit_request
this is fixed too

2016-12-25 13:00 UTC, sveredyuk approved these changes

2016-12-25 13:00 UTC, sveredyuk commented on app/controllers/visit_request/concerns/visit_request_finder.rb
> +class VisitRequest
concerns are totally bad idea in rails, it's same as callbacks.

If you want encapsulate get logic from controller, better way will be add new layer - finders.

```ruby
VisitRquest::Find.call()
VisitRquest::FindActive.call()
VisitRquest::FindWhatEverYouNeed.call()
```

2016-12-25 13:00 UTC, sveredyuk commented on app/services/visit_request/finder/attendee.rb
> +  module Finder
Sorry, but we need do not mix `services` (which represent a process of changes) with `finders`

2016-12-25 13:00 UTC, sveredyuk commented on config/routes.rb
> +      patch :cancel, to: 'visit_request/cancel#update'
patch is out-of-date REST method. I prefer to use PUT.

2016-12-25 13:38 UTC, denysmedynskyi commented on config/routes.rb
> +      patch :cancel, to: 'visit_request/cancel#update'
done

2016-12-25 13:38 UTC, denysmedynskyi commented on app/services/visit_request/finder/attendee.rb
> +  module Finder
done

2016-12-25 13:38 UTC, denysmedynskyi commented
@sveredyuk thanks for suggestions

2016-12-25 22:02 UTC, sveredyuk approved these changes

2016-12-25 22:02 UTC, sveredyuk commented on app/finders/visit_request/find.rb
> +  class Find < ApplicationService
To keep interface segregation  we need `ApplicationFinder` as root for all finders...

2016-12-25 22:02 UTC, sveredyuk commented on app/finders/visit_request/find_not_canceled.rb
> +      return unless user
```return unless user || event```

2016-12-25 22:02 UTC, sveredyuk commented on app/services/visit_request/attend.rb
> +      visit_request = VisitRequest.find_or_initialize_by(user: user, event: event)
user or event can be nil ?

2016-12-26 03:28 UTC, denysmedynskyi commented on app/services/visit_request/attend.rb
> +      visit_request = VisitRequest.find_or_initialize_by(user: user, event: event)
no. `before_authenticate!` filter and `Event.find` verify that

2016-12-26 03:28 UTC, denysmedynskyi commented on app/finders/visit_request/find_not_canceled.rb
> +      return unless user
ok

2016-12-26 03:29 UTC, denysmedynskyi commented on app/finders/visit_request/find.rb
> +  class Find < ApplicationService
ok, also it should not inherit from `ApplicationService`, yes ?

2016-12-26 06:07 UTC, denysmedynskyi commented on app/services/visit_request/attend.rb
> +      visit_request = VisitRequest.find_or_initialize_by(user: user, event: event)
oh, we are talking about service. what do you suggest ?

2016-12-26 16:39 UTC, denysmedynskyi commented
@sveredyuk any suggestions ?

2016-12-26 18:54 UTC, sveredyuk commented
@denysmedynskyi good job. rebase, squash and merge

2016-12-26 18:59 UTC, merged