[WIP] Event attendee redirection :tada:
pivorakmeetup/pivorak-web-app pull request #798
Opened 2019-08-18 17:03 UTC by skrix

### Description

There was a request for such flow that user should be redirected to rules page if clicking an attend button in the email.

2019-08-18 17:13 UTC, sveredyuk requested changes

2019-08-18 17:13 UTC, sveredyuk commented on app/controllers/visit_requests_controller.rb
> +    redirect_to '/user-agreement'
Please, use URL helpers like `user_agreement_path`

2019-08-19 17:48 UTC, skrix commented on app/controllers/visit_requests_controller.rb
> +    redirect_to '/user-agreement'
dynamically created page, have no path helpers)

2019-08-19 18:10 UTC, skrix commented on app/controllers/visit_requests_controller.rb
> +    redirect_to '/user-agreement'
but, afm code of conduct should always be created as a static page with the ability to edit content from admin page

2019-10-07 05:25 UTC, skrix commented
Registration flow will change another way.

2019-10-07 05:25 UTC, closed without merging