#824 improve watch slideshare link in talks
pivorakmeetup/pivorak-web-app pull request #837
Opened 2019-10-12 14:08 UTC by TuxujPes

Resolves [github issue](https://github.com/pivorakmeetup/pivorak-web-app/issues/x)

### Description

Describe the changes and motivations for the pull request, unless obvious from the title.

### How to test instructions

Describe how to test your changes if specs are not covering completely.

2019-10-18 09:01 UTC, skrix commented on app/assets/stylesheets/app/base/_link.scss
> -#{$namespace}--btn-slides {
Have some doubts that it was used somewhere else, not only on one button

2019-10-18 09:02 UTC, skrix commented on app/helpers/talks_helper.rb
> +    link_to 'Watch slideshare', talk.slides_url, options if talk.slides_url.present?
The text should be "Watch slides" )

2019-10-18 09:03 UTC, skrix requested changes
Need some improvement and more checks for not breaking anything

2019-10-21 11:09 UTC, TuxujPes commented
Buttons actually would like slightly different.
Unsure how https://github.com/pivorakmeetup/pivorak-web-app/pull/829 changes "Edit" button styles

![image](https://user-images.githubusercontent.com/1205052/67200214-d7920780-f40b-11e9-8bb8-38a41743c654.png)

2020-01-11 22:47 UTC, skrix commented
Thanks for your efforts, but I should close this pr for now in cause of probable rewriting of this part.

2020-01-11 22:47 UTC, closed without merging